default_platform(:ios)

platform :ios do
  lane :unit_tests do
    desc "Running Unit Tests for scheme Network-Package"
    scan(
      project: 'TorchNetwork.xcodeproj',
      scheme: 'TorchNetworkTests',                                   
      skip_detect_devices: true,       
      sdk: 'iphoneos',             
      buildlog_path: "./fastlane/fastlane-buildlog",
      configuration: 'Debug',
      derived_data_path: "./DerivedData",
      devices: ["iPhone 14"],
      code_coverage: true
    )
  end
end
